# Site
name: IB Style
description: "楽しく、ラクに、プラスになるIB lifeを。"
meta_description: "「楽しく、ラクに、プラスになるIB lifeを。」をテーマに、IB生活に役立つ情報をお届けします!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: 
email: 'mail@ibstyle.xyz'
google_analytics: 'UA-134828257-3'
disqus: 'ibstyle'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5c6cbaa79719b800115b64e4&product=sticky-share-buttons"></script>'

# Authors
authors:
  administrator:
    name: IB Style Official
    display_name: IB Style Official
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://ibstyle.tk/
    twitter: https://twitter.com/ibstyle_pr
    description: "IB Style公式アカウントです。"
  kyosuke.miyamura:
    name: Kyosuke
    display_name: Kyosuke
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/ibstyle_pr
    twitter: https://twitter.com/ibstyle_pr
    description: "準備中"
  mei.kanda:
    name: May
    display_name: May
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/mkpanda_ibs
    twitter: https://twitter.com/mkpanda_ibs
    description: "Leader and writer of IB Style. Mother tongue is Japanese. Began IB at Tamagawa Academy in grade 7 and moved to Glenlyon Norfolk School (Canada) in grade 10. HL: Math, Chemistry, Physics, English B SL: Geography, Japanese self-taught."
  shunsuke.nakayama:
    name: Shunsuke
    display_name: Shunsuke
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/ibstyle_pr
    twitter: https://twitter.com/ibstyle_pr
    description: "準備中"
  koiki.kishi:
    name: Koiki
    display_name: Koiki
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/ibstyle_pr
    twitter: https://twitter.com/ibstyle_pr
    description: "準備中"
  junya.eriguchi:
    name: Junya
    display_name: Junya
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/ibstyle_pr
    twitter: https://twitter.com/ibstyle_pr
    description: "準備中"
  manami.fukushima:
    name: Manami
    display_name: Manami
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/ibstyle_pr
    twitter: https://twitter.com/ibstyle_pr
    description: "準備中"
  miyu.osamura:
    name: Miyu
    display_name: Miyu
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/yooonmiyeon
    twitter: https://twitter.com/yooonmiyeon
    description: "Writer of IB Style. Moved to America from 5th grade. Move back to Japan in 8th grade (IB school). Moved to Canada from 11th grade to finish DP program at Glenlyon Norfolk School. Can speak both Japanese and English."
  ami.okazaki:
    name: Ami
    display_name: Ami
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://twitter.com/ibstyle_pr
    twitter: https://twitter.com/ibstyle_pr
    description: "玉川学園の幼稚部から通い、中学1年生の時IBコースに進学。DPではEconomics、Japanese (Literature)、Visual ArtのHLとEnglish (Language and Literature)、ESS、MathのSLを履修。2019年9月からボストン大学 芸術学部 舞台芸術学科に進学予定。"
  hiromi.egusa:
    name: Hiromi
    display_name: HEYO
    gravatar: 8e7606fcd12b7f2855455f8fba0bbfa2f
    web: https://heyo7777.hatenablog.com/
    twitter: https://twitter.com/HeyoIB_Heyo
    description: "Writer of IB Style. Japanese native speaker. Spent my elementary and middle school years in Japan, Australia and Cameroon. Started IB Diploma Programme in 11th grade, at an international school in Senegal, West Africa. HL: History, Visual Arts, English Literature A SL: Math, Physics, French abinitio"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
permalink: '/posts/:slug/'
markdown: kramdown
highlighter: rouge
